// installments.ts — splitting a payment plan into instalments, and
// working out when each one falls due.
//
// This used to live inside a click handler in Billing.tsx, which meant
// the arithmetic that decides what a patient owes each month could not
// be tested. Clinic money must be exactly right, so it moved here.
//
// Two rules govern the file:
//   1. The instalments must sum to the plan total. Exactly. Not "close
//      after rounding" — the patient pays the sum of the rows, so if the
//      rows do not add up to the agreed total, someone is short-changed.
//   2. A due date must never silently jump a month.

/**
 * Splits a total into `count` instalments whose sum is exactly the total.
 *
 * Every instalment is rounded to whole toman except the last, which
 * absorbs whatever the rounding left over. A plan of 1,000,000 over 3
 * becomes 333,333 + 333,333 + 333,334, not three times 333,333 with 1
 * toman quietly lost.
 *
 * The remainder lands on the LAST instalment rather than the first
 * because the patient meets the first one immediately; a first payment
 * that does not match the number they were quoted starts an argument at
 * the desk, while a final one that is a few toman different does not.
 */

import { toJalali, jalaliToGregorian, jalaliMonthLength } from './persianDate'
export function splitAmount(total: number, count: number): number[] {
  if (!Number.isFinite(total) || !Number.isFinite(count)) return []
  const n = Math.floor(count)
  if (n < 1) return []
  const safeTotal = Math.round(total)
  if (n === 1) return [safeTotal]

  const each = Math.round(safeTotal / n)
  const head = Array.from({ length: n - 1 }, () => each)
  const last = safeTotal - each * (n - 1)
  return [...head, last]
}

/**
 * MOD-FIX-014 | سررسیدهای ماهانه — با ماه شمسی
 *
 * A clinic and its patients agree instalments in Jalali months. This
 * function used to step Gregorian months instead, and because Jalali
 * months are 31, 30 and 29 days long while Gregorian ones are 31, 30 and
 * 28, the Jalali day of the month slid as the plan ran. A patient told
 * «اول هر ماه» saw due dates land on the 1st, 1st, 2nd, 2nd, 3rd, 4th…
 *
 * Storage stays ISO Gregorian — the database column is a `date` and every
 * other part of the app reads it that way. Only the arithmetic moved to
 * the Persian calendar, which is where the agreement actually lives.
 *
 * The day is clamped to the end of the target Jalali month rather than
 * allowed to roll forward. A plan starting 31 Farvardin has no 31st in
 * Mehr; landing on 1 Aban would move a payment by a whole month, which is
 * a real dispute with a patient, not a rounding detail.
 */
export function installmentDueDates(startISO: string, count: number): string[] {
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(startISO)
  const n = Math.floor(count)
  if (!m || n < 1) return []

  const [jy, jm, jd] = toJalali(Number(m[1]), Number(m[2]), Number(m[3]))

  return Array.from({ length: n }, (_, i) => {
    const absolute = jm - 1 + i
    const year = jy + Math.floor(absolute / 12)
    const month = (absolute % 12) + 1
    const day = Math.min(jd, jalaliMonthLength(year, month))
    const iso = jalaliToGregorian(year, month, day)
    // MOD-FIX-020: jalaliToGregorian now returns null on an impossible
    // date. It cannot happen here — month is 1..12 by construction and
    // day is clamped to that month's real length — but a silently
    // dropped instalment is a financial error nobody would notice, so
    // this refuses loudly rather than returning a shorter schedule.
    if (!iso) throw new Error(`سررسید نامعتبر ساخته شد: ${year}/${month}/${day}`)
    return iso
  })
}

export interface PlannedInstallment {
  installment_number: number
  amount: number
  due_date: string
}

/** Builds the full schedule. One call so the amounts and the dates can
 * never be generated by two different code paths that disagree. */
export function buildSchedule(total: number, count: number, startISO: string): PlannedInstallment[] {
  const amounts = splitAmount(total, count)
  const dates = installmentDueDates(startISO, amounts.length)
  return amounts.map((amount, i) => ({
    installment_number: i + 1,
    amount,
    due_date: dates[i],
  }))
}

export interface LedgerInstallment {
  amount: number | null
  status: string
  due_date: string
}

/** Statuses that mean the money arrived. */
const SETTLED = new Set(['paid', 'completed', 'cleared'])
/** Statuses that mean this row no longer expects money. */
const VOIDED = new Set(['cancelled', 'void'])

export interface PlanProgress {
  total: number
  paid: number
  remaining: number
  paidCount: number
  dueCount: number
  overdueCount: number
  /** The earliest unpaid due date, or null when nothing is outstanding. */
  nextDue: string | null
}

/**
 * Where a plan stands today.
 *
 * `total` is the sum of the live instalment rows, not the plan header's
 * total_amount. If an instalment was edited after the plan was created
 * the two disagree, and the rows are what the patient is actually being
 * asked to pay.
 */
export function planProgress(installments: LedgerInstallment[], todayISO: string): PlanProgress {
  const live = installments.filter((i) => !VOIDED.has(i.status))
  let total = 0
  let paid = 0
  let paidCount = 0
  let overdueCount = 0
  let nextDue: string | null = null

  for (const i of live) {
    const amount = i.amount || 0
    total += amount
    if (SETTLED.has(i.status)) {
      paid += amount
      paidCount += 1
      continue
    }
    if (i.due_date && i.due_date < todayISO) overdueCount += 1
    if (i.due_date && (nextDue === null || i.due_date < nextDue)) nextDue = i.due_date
  }

  return {
    total,
    paid,
    remaining: total - paid,
    paidCount,
    dueCount: live.length - paidCount,
    overdueCount,
    nextDue,
  }
}

export interface ReconcileInput {
  planTotal: number
  installments: LedgerInstallment[]
}

export interface Reconciliation {
  ok: boolean
  planTotal: number
  installmentTotal: number
  difference: number
  message: string | null
}

/**
 * Checks that the instalment rows still add up to the plan they belong
 * to.
 *
 * Returns the difference rather than silently correcting either side.
 * The clinic has to decide which number is right — the agreed plan or
 * the edited rows — and a function that quietly picks one would hide a
 * disagreement about money.
 */
export function reconcilePlan({ planTotal, installments }: ReconcileInput): Reconciliation {
  const live = installments.filter((i) => !VOIDED.has(i.status))
  const installmentTotal = live.reduce((s, i) => s + (i.amount || 0), 0)
  const difference = installmentTotal - Math.round(planTotal)
  if (difference === 0) {
    return { ok: true, planTotal, installmentTotal, difference: 0, message: null }
  }
  return {
    ok: false,
    planTotal,
    installmentTotal,
    difference,
    message:
      difference > 0
        ? 'مجموع اقساط از مبلغ طرح بیشتر است'
        : 'مجموع اقساط از مبلغ طرح کمتر است',
  }
}
